### ISSUE TITLE
Brilliant!

### ISSUE THREAD

**Issue by peterpolidoro** [countvajhula/rigpa#1]
This is such a fantastic idea! I loved your EmacsConf 2020 talk. This makes me want to modify my entire Emacs setup that I have been using for many years to use this instead.

I am curious about your future plans for this package.

This is probably an annoying question, but do you think your code could be made independent from evil mode? It would be great if a user could select whether or not they would like to depend on evil mode and use its key bindings or use more traditional Emacs keybindings or something totally custom.

Right now it seems like the key bindings are pretty deeply embedded into each mode. It seems like all bindings would have to be changed in each mode in order to switch from evil bindings to Emacs bindings. That could require a huge amount of configuration if the user does not want to use your default settings.

It might be nice to have some more generalized motion primitives with key bindings for those set in one place, something like "forward", "backward", "up", "down", etc. Then the same key could be used for "forward" in every mode and every mode would just change what "forward" means, saving you from having to put a specific key binding into each mode. There would still need to be unique key bindings for some modes, but it would be great to reuse as many as possible for every mode. I am not sure what all of the other generalized primitives would be, what else tends to be common in all of your modes?

Another awesome feature would be to have the option of seeing where all of the motion commands will move for each mode, like how you can see where you are about to jump in [avy mode](https://github.com/abo-abo/avy). Like if you had the "h" key assigned to "backward" and "l" assigned to "forward", in word mode the letter "h" would be on top of the previous word and "l" would be on top of the next word, showing you where you would jump if you pressed those keys. In line mode the "h" and "l" would be on the previous line and next line, in window mode they would be on each of the windows where you would jump, etc. Every time you switched modes, those indicators would jump to their new locations. That would give really useful super fast feedback on where you can move without having to look down at the mode line to see what mode you are in or have to remember exactly what each mode means.

Thank you so much for your great idea and amazing work!

**Comment by countvajhula** [comment]
Hi @peterpolidoro ! Thank you for your kind words. I'm glad you enjoyed the talk and are interested in the package!

> This is probably an annoying question, but do you think your code could be made independent from evil mode? It would be great if a user could select whether or not they would like to depend on evil mode and use its key bindings or use more traditional Emacs keybindings or something totally custom.

This is a good question! Initially I thought the package would be a generalization of evil mode, but over time it's become clear that it's better to just define a framework that can connect together various different ideas of "modes" without providing any strong definitions of what those modes should look like, aside from conventions and guidelines for certain classes of modes (e.g. "noun modes" would have conventions that should ideally be followed). All this is to say that yes, absolutely, evil should not be a dependency of this package.

> Right now it seems like the key bindings are pretty deeply embedded into each mode. It seems like all bindings would have to be changed in each mode in order to switch from evil bindings to Emacs bindings. That could require a huge amount of configuration if the user does not want to use your default settings.
> It might be nice to have some more generalized motion primitives with key bindings for those set in one place, something like "forward", "backward", "up", "down", etc. Then the same key could be used for "forward" in every mode and every mode would just change what "forward" means, saving you from having to put a specific key binding into each mode. There would still need to be unique key bindings for some modes, but it would be great to reuse as many as possible for every mode. I am not sure what all of the other generalized primitives would be, what else tends to be common in all of your modes?

Yeah I think we should be able to do it this way for all modes that adhere to the keybinding conventions (i.e. noun modes), where we should be able to set the common bindings for all modes in one place. It may be some time before this is available though, so in the meantime, for all of the hydra-based modes (this is most of the modes atm), you could use the [defhydra+](https://oremacs.com/2019/05/18/hydra-0.15.0/) macro to override the default bindings for each mode individually. Re: other things that tend to be common - take a look at the [keybinding model](https://github.com/countvajhula/rigpa/blob/master/Keybinding_Model.rst) document for more of those. It's still very much a work in progress and may change a lot over time. But, as you were getting at, the important thing is that there will be some "ideas" that will be captured there, and the specific keybindings would be in terms of these ideas, and could be customized by the user.

> Another awesome feature would be to have the option of seeing where all of the motion commands will move for each mode, like how you can see where you are about to jump in avy mode. Like if you had the "h" key assigned to "backward" and "l" assigned to "forward", in word mode the letter "h" would be on top of the previous word and "l" would be on top of the next word, showing you where you would jump if you pressed those keys. In line mode the "h" and "l" would be on the previous line and next line, in window mode they would be on each of the windows where you would jump, etc. Every time you switched modes, those indicators would jump to their new locations. That would give really useful super fast feedback on where you can move without having to look down at the mode line to see what mode you are in or have to remember exactly what each mode means.

I am all for [feedback](https://givegoodux.com/feedback-5-principles-interaction-design-supercharge-ui-5-5/) as a design principle, and it's definitely something I'm interested in supporting in a formal way. I'm not sure what specific forms feedback will take, but something like what you're suggesting could certainly be useful for some people / some cases. It's very early to speculate about this, obviously, but I would ideally prefer most forms of feedback to be done as "side effects" of the core functionality. That way, anyone can implement different forms of feedback that may occur to them, and we don't need to have a one-size-fits-all solution. A good example of this kind of approach is [evil-goggles](https://github.com/edkolev/evil-goggles), which provides visual feedback on evil operations but isn't part of the evil core. If done right we could even have different types of feedback seamlessly combined.

Thanks for your input! If you want to try the package in its current form (which I use day to day), you could either (1) wait until I have time to put up some pre-release installation instructions in the README, or (2) use something like [Chemacs](https://github.com/plexus/chemacs) and just download my [.emacs.d](https://github.com/countvajhula/.emacs.d) repo. I recently moved to [straight.el](https://github.com/raxod502/straight.el) so in theory the config should just work out of the box, but I haven't tested it ;) But I bet you have tons of config you'd like to retain, so if that's the case, you can wait for option (1), which I'll hopefully get to soon.

**Comment by peterpolidoro** [comment]
Yes I totally agree with all of this. This is a generalization of evil mode, but your idea of being able to quickly navigate through a multidimensional space of modes is so powerful that you should not limit it to anything too specific. All keybindings and feedback and details like that should be specified outside of your more generalized framework.

If done correctly, I could imagine this package becoming super popular and used in ways that may be hard to guess now.

Figuring out which "ideas" get shared between modes seems like a real challenge. It would be wonderful if somehow even that set of ideas could be easily modifiable so it can be iterated over time and adapted by individual users. Maybe if a large enough community of people iterate over the set enough times a few fundamental ones would emerge that will work for almost every mode. Or perhaps some modes have already have already figured out or if you looked at enough packages you could see what they have in common.

I wish I was an expert elisp programmer so I could help you work on this. It seems important to implement it really well though so it can be used in a fundamental way throughout all of Emacs.

I really liked the name indra by the way. Perhaps reconsider renaming your package back to that. Your description of Indra's net was such a great metaphor and made it easier to visualize the concepts. There are so many nice images and representations of Indra's net that you could use for your package graphics and icons. Just a thought. Thanks again and I look forward to seeing how this progresses!

**Comment by countvajhula** [comment]
Right on, I'll take your suggestions into consideration. Re: contributing, as the library becomes more stable I intend to create issues for features / components to add with a spec of what's needed. That should help interested contributors get started. And in the meantime if anything occurs to you feel free to create another issue or comment below. Thanks again and stay tuned :)

**Comment by black7375** [comment]
I know it's difficult, but when do you expect a stable release?

The idea of keybinding is interesting.
Thank you for your effort.

**Comment by countvajhula** [comment]
@black7375 thanks for your interest. As for when there will be a MELPA-ready release, it's tough to say. There are a few foundational changes I want to make before that point, such as properly differentiating "change in perspective" from "change in reference level" and maybe make some of these meta navigation commands more spatial (e.g. using `h j k l` in some form). The point at which I feel that there won't be any major "backwards incompatible" changes, I think is the point when it's MELPA ready. We're not there yet 😄

But the good news is that I've added pre-release install instructions to the [README](https://github.com/countvajhula/rigpa/blob/master/README.rst) so you can give it a go right away! This the configuration I use on a daily basis, so it's unlikely to be broken, even though the UI may change without warning.

**Comment by black7375** [comment]
Thank you for your kind answer.
I'm happy to try it out right now. :+1:  :+1:  :+1:

**Comment by countvajhula** [comment]
@black7375 Excellent, please let me know if you run into any issues.

**Comment by gutofarias** [comment]
Your package is really brilliant! Thank you for all the effort involved. I hope to start using it soon!

**Comment by countvajhula** [comment]
Thanks for the kind words @gutofarias 🙏  Please let me know if you run into any issues, I'm happy to help.
