### ISSUE TITLE
Missing parsec package in Package-Requires

### ISSUE THREAD

**Issue by aancel** [countvajhula/rigpa#2]
Hello,

I'd like to report that the `parsec` package seems to be missing from the Packages-Requires dependencies in: https://github.com/countvajhula/rigpa/blob/master/rigpa.el.
I've tried to install the package with straight.el and ended up with the following error:
```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "Aucun fichier ou dossier de ce type" "parsec")
  require(parsec)
  ...
```

P.S. Thanks for your presentation at EmacsConf 2020, I really enjoyed it !

**Comment by countvajhula** [comment]
Thanks for the report @aancel ! I've added the parsec dependency. Does it build now?

**Comment by aancel** [comment]
Yes, thanks you, this issue has been fixed !
