### ISSUE TITLE
Package doesn't build when Consolas font not installed

### ISSUE THREAD

**Issue by bgturner** [countvajhula/rigpa#6]
I'm on an Ubuntu box and don't have Consolas installed. Because the Consolas font is attempting to be set on line 68 of `rigpa.el`, I wasn't able to build rigpa until I commented out that line:

https://github.com/countvajhula/rigpa/blob/master/rigpa.el#L68

**Comment by countvajhula** [comment]
Thanks for the report! I've changed it to check for Consolas and otherwise default to Courier New, which is generally considered safe (e.g. https://web.mit.edu/jmorzins/www/fonts.html).

**Comment by markgdawson** [comment]
I attempted to use this on a system which didn't have `Courier New` (at least didn't have it available to Emacs). And I ran into the same issue.

Would it make sense to default to whatever font is used by `default`? Or avoid setting a font at all?

**Comment by countvajhula** [comment]
Good idea @markgdawson , I've changed it to check if Courier exists before setting it (it does ideally need to be a monospace font), but otherwise use the `default` font.

**Comment by countvajhula** [comment]
Pretty sure these issues should be resolved with #7 . Feel free to reopen if there are further issues 👍
